stages:
  data_ingestion:
    cmd: python src/components/data_ingestion.py
    deps:
      - src/components/data_ingestion.py
      - src/utils/utils.py
      - src/utils/logging.py
      - src/utils/exception.py
      - params.yaml
    outs:
      - data/raw/train.csv
      - data/raw/test.csv
  
  feature_engineering:
    cmd: python src/components/feature_engineering.py
    deps:
      - src/components/feature_engineering.py
      - src/utils/utils.py
      - src/utils/logging.py
      - src/utils/exception.py
      - params.yaml
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_engineered.csv
      - data/processed/test_engineered.csv
  
  xgboost_model_building:
    cmd: python src/components/model_building.py
    deps:
      - src/components/model_building.py
      - src/utils/utils.py
      - src/utils/logging.py
      - src/utils/exception.py
      - data/processed/train_engineered.csv
      - data/processed/test_engineered.csv
    outs:
      - models/xgboost/xgboost_model.pkl
      - models/xgboost/scaler.pkl
      - models/xgboost/model_metadata.json