data_ingestion:
  database_path: "J:/mlops_revisited/frieght_price_prediction/data/inventory.db"
  tables:
    - vendor_invoice
    - purchase_prices
    - purchases
    - begin_inventory
    - end_inventory
  test_size: 0.2
  random_state: 42